spring:
  application:
    name: connections-service

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password

server:
  servlet:
    context-path: /connections
  port: 9030

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka